import type { IPostItem } from 'src/types/blog';

// ----------------------------------------------------------------------

const AVATAR_PATH = '/assets/images/avatars/synthetic';

export const BLOG_MOCK: IPostItem[] = [
  // --- ECONOMIA (7 Posts) ---
  {
    id: '1',
    title: 'A Revolução do RWA: Como a ASPPIBRA está transformando ativos reais em tokens',
    slug: 'revolucao-rwa-asppibra',
    description: 'Descubra como a tecnologia blockchain está democratizando o acesso a propriedades rurais e urbanas no Brasil.',
    content: `<p>A tokenização de ativos reais (RWA) não é mais uma promessa do futuro...</p>`,
    coverUrl: '/assets/images/covers/Economia-Fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date().toISOString(),
    totalViews: 15400,
    totalShares: 850,
    totalComments: 45,
    totalFavorites: 320,
    metaTitle: 'A Revolução do RWA | ASPPIBRA DAO',
    metaDescription: 'Entenda como a ASPPIBRA DAO utiliza blockchain para ativos reais.',
    metaKeywords: ['RWA', 'Blockchain', 'Imóveis', 'DAO'],
    tags: ['RWA', 'Agro', 'Inovação'],
    featured: true,
    author: { name: 'Arthur Guimarães', avatarUrl: `${AVATAR_PATH}/arthur_guimaraes.png` },
    comments: [],
    favoritePerson: [{ name: 'Carolina Alves', avatarUrl: `${AVATAR_PATH}/carolina_alves.png` }],
  },
  {
    id: '2',
    title: 'O Mercado Imobiliário na Era da Web3',
    slug: 'mercado-imobiliario-web3',
    description: 'Como a liquidez dos tokens está mudando o investimento em imóveis.',
    content: '<p>O mercado imobiliário tradicional sempre foi conhecido pela baixa liquidez...</p>',
    coverUrl: '/assets/images/covers/MercadoImobiliario-Fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    totalViews: 8900,
    totalShares: 120,
    totalComments: 12,
    totalFavorites: 420,
    metaTitle: 'Mercado Imobiliário Web3 | ASPPIBRA DAO',
    metaDescription: 'Liquidez e tokens no setor imobiliário.',
    metaKeywords: ['Imóveis', 'RWA', 'Web3'],
    tags: ['Imóveis', 'Tokens'],
    author: { name: 'Thiago Mendes', avatarUrl: `${AVATAR_PATH}/thiago_mendes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '3',
    title: 'Commodities e o Futuro da Cadeia de Suprimentos',
    slug: 'commodities-futuro-suprimentos',
    description: 'Análise técnica sobre a tokenização de soja, milho e gado.',
    content: '<p>As commodities agrícolas representam a força do PIB brasileiro...</p>',
    coverUrl: '/assets/images/covers/Commodities-Fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    totalViews: 6500,
    totalShares: 300,
    totalComments: 8,
    totalFavorites: 150,
    metaTitle: 'Commodities Blockchain | ASPPIBRA DAO',
    metaDescription: 'Tokenização no agronegócio.',
    metaKeywords: ['Commodities', 'Agro', 'Blockchain'],
    tags: ['Agro', 'Supply Chain'],
    author: { name: 'Arthur Guimarães', avatarUrl: `${AVATAR_PATH}/arthur_guimaraes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '4',
    title: 'Criptomoedas e a Nova Economia Digital',
    slug: 'criptomoedas-nova-economia',
    description: 'Entenda como o Bitcoin se tornou um ativo de reserva para as DAOs.',
    content: '<p>A economia digital não é mais um nicho de entusiastas de tecnologia...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    totalViews: 12100,
    totalShares: 450,
    totalComments: 22,
    totalFavorites: 540,
    metaTitle: 'Criptomoedas e Economia | ASPPIBRA DAO',
    metaDescription: 'O papel do Bitcoin nas DAOs.',
    metaKeywords: ['Bitcoin', 'Economia', 'Digital'],
    tags: ['Bitcoin', 'Web3'],
    author: { name: 'Carolina Alves', avatarUrl: `${AVATAR_PATH}/carolina_alves.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '5',
    title: 'A Geopolítica das Moedas Fiat vs Stablecoins',
    slug: 'moedas-fiat-vs-stablecoins',
    description: 'Por que o mundo está migrando para o dólar digital e stablecoins de RWA.',
    content: '<p>As moedas fiduciárias estão enfrentando um desafio sem precedentes...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    totalViews: 9800,
    totalShares: 210,
    totalComments: 15,
    totalFavorites: 320,
    metaTitle: 'Moedas Fiat vs Stablecoins | ASPPIBRA DAO',
    metaDescription: 'Desdolarização e tokens estáveis.',
    metaKeywords: ['Fiat', 'Stablecoin', 'Dólar'],
    tags: ['Geopolítica', 'Finanças'],
    author: { name: 'Rafael Costa', avatarUrl: `${AVATAR_PATH}/rafael_costa.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '6',
    title: 'O Petróleo e a Transição Energética da DAO',
    slug: 'petroleo-transicao-energetica',
    description: 'Como os lucros de energia fóssil estão financiando a infraestrutura verde.',
    content: '<p>A energia é o motor de qualquer economia, inclusive a descentralizada...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    totalViews: 4500,
    totalShares: 180,
    totalComments: 9,
    totalFavorites: 110,
    metaTitle: 'Petróleo e Energia | ASPPIBRA DAO',
    metaDescription: 'Sustentabilidade e investimentos em energia.',
    metaKeywords: ['Petróleo', 'Energia', 'ESG'],
    tags: ['Energia', 'ESG'],
    author: { name: 'Eleonora Bittencourt', avatarUrl: `${AVATAR_PATH}/eleonora_bittencourt.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '7',
    title: 'Banner Destaque: O Ecossistema ASPPIBRA DAO',
    slug: 'banner-destaque-asppibra',
    description: 'Visão geral de todos os ativos sob gestão da nossa governança.',
    content: '<p>Nosso ecossistema cresce a cada dia com a ajuda dos cidadãos...</p>',
    coverUrl: '/assets/images/covers/banner-fallback.png',
    category: 'Economia',
    status: 'published',
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    totalViews: 18000,
    totalShares: 1500,
    totalComments: 85,
    totalFavorites: 1200,
    metaTitle: 'Ecossistema ASPPIBRA DAO',
    metaDescription: 'Transparência e ativos tokenizados.',
    metaKeywords: ['Ecossistema', 'DAO', 'Transparência'],
    tags: ['DAO', 'Comunidade'],
    author: { name: 'Leonardo Ferraz', avatarUrl: `${AVATAR_PATH}/leonardo_ferraz.png` },
    comments: [],
    favoritePerson: [],
  },

  // --- TECNOLOGIA (7 Posts) ---
  {
    id: '8',
    title: 'Smart Contracts: A Base Jurídica do Futuro',
    slug: 'smart-contracts-base-juridica',
    description: 'Como eliminamos intermediários através de código auditável e seguro.',
    content: '<p>O código é a lei na nova economia descentralizada...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    totalViews: 9800,
    totalShares: 400,
    totalComments: 18,
    totalFavorites: 290,
    metaTitle: 'Smart Contracts | ASPPIBRA DAO',
    metaDescription: 'Segurança técnica e jurídica.',
    metaKeywords: ['Código', 'Smart Contracts', 'Segurança'],
    tags: ['Blockchain', 'Código'],
    author: { name: 'Leonardo Ferraz', avatarUrl: `${AVATAR_PATH}/leonardo_ferraz.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '9',
    title: 'Inteligência Artificial na Gestão de Tesouraria',
    slug: 'ia-gestao-tesouraria',
    description: 'Utilizando algoritmos para otimizar a liquidez dos ativos RWA.',
    content: '<p>A IA agora atua como um co-piloto para nossos governantes...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    totalViews: 5400,
    totalShares: 150,
    totalComments: 5,
    totalFavorites: 120,
    metaTitle: 'IA e Tesouraria | ASPPIBRA DAO',
    metaDescription: 'Algoritmos e Liquidez.',
    metaKeywords: ['IA', 'Finanças', 'Algoritmos'],
    tags: ['IA', 'FinTech'],
    author: { name: 'Eleonora Bittencourt', avatarUrl: `${AVATAR_PATH}/eleonora_bittencourt.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '10',
    title: 'Nós de Rede e a Descentralização Global',
    slug: 'nos-rede-descentralizacao',
    description: 'Como manter a resiliência da rede ASPPIBRA em cenários extremos.',
    content: '<p>A descentralização física é tão importante quanto a digital...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    totalViews: 3200,
    totalShares: 90,
    totalComments: 2,
    totalFavorites: 85,
    metaTitle: 'Resiliência de Rede | ASPPIBRA DAO',
    metaDescription: 'Infraestrutura descentralizada.',
    metaKeywords: ['Rede', 'Infraestrutura', 'Nós'],
    tags: ['Infra', 'Segurança'],
    author: { name: 'Helena Moraes', avatarUrl: `${AVATAR_PATH}/helena_moraes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '17',
    title: 'Cibersegurança e Proteção de Ativos Digitais',
    slug: 'ciberseguranca-protecao-ativos',
    description: 'Protocolos de segurança máxima para a custódia de tokens RWA.',
    content: '<p>A segurança é o pilar mais importante da nossa infraestrutura...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    totalViews: 6700,
    totalShares: 210,
    totalComments: 14,
    totalFavorites: 320,
    metaTitle: 'Cibersegurança | ASPPIBRA DAO',
    metaDescription: 'Proteção on-chain.',
    metaKeywords: ['Segurança', 'Ciber', 'Ativos'],
    tags: ['Segurança', 'Blockchain'],
    author: { name: 'Thiago Mendes', avatarUrl: `${AVATAR_PATH}/thiago_mendes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '18',
    title: 'Interoperabilidade entre Blockchains L1 e L2',
    slug: 'interoperabilidade-l1-l2',
    description: 'Como a ASPPIBRA conecta diferentes redes para máxima liquidez.',
    content: '<p>O futuro é multi-chain e estamos preparados para isso...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    totalViews: 4100,
    totalShares: 120,
    totalComments: 3,
    totalFavorites: 95,
    metaTitle: 'Interoperabilidade | ASPPIBRA DAO',
    metaDescription: 'Multi-chain e liquidez.',
    metaKeywords: ['Multi-chain', 'L2', 'Bridge'],
    tags: ['Tecnologia', 'Interoperabilidade'],
    author: { name: 'Felipe Rios', avatarUrl: `${AVATAR_PATH}/felipe_rios.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '19',
    title: 'Identidade Soberana (DID) e o Cidadão Digital',
    slug: 'identidade-soberana-did',
    description: 'O controle total dos seus dados de volta para você.',
    content: '<p>A identidade digital é o primeiro passo para a liberdade financeira...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    totalViews: 8900,
    totalShares: 500,
    totalComments: 28,
    totalFavorites: 450,
    metaTitle: 'Identidade Digital | ASPPIBRA DAO',
    metaDescription: 'Soberania e Privacidade.',
    metaKeywords: ['DID', 'Identidade', 'Privacidade'],
    tags: ['Privacidade', 'DID'],
    author: { name: 'Arthur Guimarães', avatarUrl: `${AVATAR_PATH}/arthur_guimaraes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '20',
    title: 'Computação em Nuvem Descentralizada',
    slug: 'computacao-nuvem-descentralizada',
    description: 'Hospedando a governança da DAO em servidores impossíveis de censurar.',
    content: '<p>Nossa infraestrutura não depende de grandes provedores centralizados...</p>',
    coverUrl: '/assets/images/covers/Criptomoedas-Fallback.png',
    category: 'Tecnologia',
    status: 'published',
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    totalViews: 3500,
    totalShares: 80,
    totalComments: 2,
    totalFavorites: 70,
    metaTitle: 'Nuvem Web3 | ASPPIBRA DAO',
    metaDescription: 'Resiliência contra censura.',
    metaKeywords: ['Nuvem', 'Web3', 'Censura'],
    tags: ['Infra', 'Web3'],
    author: { name: 'Helena Moraes', avatarUrl: `${AVATAR_PATH}/helena_moraes.png` },
    comments: [],
    favoritePerson: [],
  },

  // --- GEOPOLÍTICA (7 Posts) ---
  {
    id: '11',
    title: 'O Impacto dos BRICS na Economia Interplanetária',
    slug: 'impacto-brics-economia',
    description: 'Análise sobre a desdolarização e o surgimento de novos blocos econômicos.',
    content: '<p>O cenário geopolítico está mudando rapidamente...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    totalViews: 18500,
    totalShares: 1200,
    totalComments: 95,
    totalFavorites: 890,
    metaTitle: 'BRICS e Economia | ASPPIBRA DAO',
    metaDescription: 'Mudanças no cenário financeiro global.',
    metaKeywords: ['BRICS', 'Geopolítica', 'Global'],
    tags: ['Global', 'Economia'],
    author: { name: 'Rafael Costa', avatarUrl: `${AVATAR_PATH}/rafael_costa.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '12',
    title: 'Regulamentação Cripto no Brasil em 2026',
    slug: 'regulamentacao-cripto-brasil-2026',
    description: 'Como o Brasil se tornou o hub de ativos digitais da América Latina.',
    content: '<p>Novas leis trazem segurança jurídica para investidores e produtores...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 129600000).toISOString(),
    totalViews: 7100,
    totalShares: 340,
    totalComments: 25,
    totalFavorites: 410,
    metaTitle: 'Regulação Brasil | ASPPIBRA DAO',
    metaDescription: 'Leis e Ativos Digitais.',
    metaKeywords: ['Leis', 'Brasil', 'Regulação'],
    tags: ['Legal', 'Brasil'],
    author: { name: 'Arthur Guimarães', avatarUrl: `${AVATAR_PATH}/arthur_guimaraes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '13',
    title: 'Soberania Digital e a Proteção de Dados',
    slug: 'soberania-digital-protecao-dados',
    description: 'A luta pelo controle da informação na era das IAs centralizadas.',
    content: '<p>Quem controla os dados, controla o futuro...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 216000000).toISOString(),
    totalViews: 4200,
    totalShares: 110,
    totalComments: 6,
    totalFavorites: 135,
    metaTitle: 'Soberania Digital | ASPPIBRA DAO',
    metaDescription: 'Privacidade e Controle.',
    metaKeywords: ['Privacidade', 'Dados', 'Soberania'],
    tags: ['Privacidade', 'Web3'],
    author: { name: 'Helena Moraes', avatarUrl: `${AVATAR_PATH}/helena_moraes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '21',
    title: 'Tratados Internacionais de Comércio via DAO',
    slug: 'tratados-internacionais-dao',
    description: 'Como as DAOs estão substituindo acordos bilaterais tradicionais.',
    content: '<p>O comércio internacional agora é peer-to-peer entre governanças...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 302400000).toISOString(),
    totalViews: 5900,
    totalShares: 180,
    totalComments: 8,
    totalFavorites: 210,
    metaTitle: 'Comércio DAO | ASPPIBRA DAO',
    metaDescription: 'Novas relações internacionais.',
    metaKeywords: ['Comércio', 'Tratado', 'DAO'],
    tags: ['Economia', 'Global'],
    author: { name: 'Carolina Alves', avatarUrl: `${AVATAR_PATH}/carolina_alves.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '22',
    title: 'A Moeda Comum do Sul: CBDCs e Estabilidade',
    slug: 'moeda-comum-sul-cbdc',
    description: 'O papel das moedas digitais de bancos centrais na integração regional.',
    content: '<p>A estabilidade monetária agora é algorítmica e regionalizada...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 388800000).toISOString(),
    totalViews: 9200,
    totalShares: 420,
    totalComments: 31,
    totalFavorites: 560,
    metaTitle: 'CBDC Regional | ASPPIBRA DAO',
    metaDescription: 'Moedas digitais e o Sul Global.',
    metaKeywords: ['CBDC', 'América Latina', 'Moeda'],
    tags: ['Finanças', 'Geopolítica'],
    author: { name: 'Rafael Costa', avatarUrl: `${AVATAR_PATH}/rafael_costa.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '23',
    title: 'Conflitos Cibernéticos e a Defesa de DAOs',
    slug: 'conflitos-ciberneticos-defesa-dao',
    description: 'Como nos protegemos de ataques de Estados-nação contra nossa tesouraria.',
    content: '<p>A guerra agora acontece no nível do protocolo...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 475200000).toISOString(),
    totalViews: 11000,
    totalShares: 800,
    totalComments: 45,
    totalFavorites: 920,
    metaTitle: 'Defesa Cibernética | ASPPIBRA DAO',
    metaDescription: 'Segurança em nível de Estado.',
    metaKeywords: ['Ciber', 'Defesa', 'Guerra'],
    tags: ['Segurança', 'Global'],
    author: { name: 'Isabella Viana', avatarUrl: `${AVATAR_PATH}/isabella_viana.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '24',
    title: 'O Fim das Fronteiras Fiscais para Ativos Digitais',
    slug: 'fim-fronteiras-fiscais',
    description: 'A globalização total da liquidez e seus desafios regulatórios.',
    content: '<p>O capital agora flui livremente através de fronteiras digitais...</p>',
    coverUrl: '/assets/images/covers/MoedasFiates-Fallback.png',
    category: 'Geopolítica',
    status: 'published',
    createdAt: new Date(Date.now() - 561600000).toISOString(),
    totalViews: 6300,
    totalShares: 150,
    totalComments: 9,
    totalFavorites: 180,
    metaTitle: 'Globalização Digital | ASPPIBRA DAO',
    metaDescription: 'Liquidez sem fronteiras.',
    metaKeywords: ['Fiscal', 'Fronteiras', 'Liquidez'],
    tags: ['Economia', 'Futuro'],
    author: { name: 'Thiago Mendes', avatarUrl: `${AVATAR_PATH}/thiago_mendes.png` },
    comments: [],
    favoritePerson: [],
  },

  // --- MEIO AMBIENTE (7 Posts) ---
  {
    id: '14',
    title: 'Créditos de Carbono: O Novo Ouro Verde',
    slug: 'creditos-carbono-ouro-verde',
    description: 'Como os produtores da ASPPIBRA estão sendo remunerados por preservar a floresta.',
    content: '<p>A sustentabilidade agora é lucrativa através da tokenização...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    totalViews: 12500,
    totalShares: 900,
    totalComments: 55,
    totalFavorites: 670,
    metaTitle: 'Créditos de Carbono | ASPPIBRA DAO',
    metaDescription: 'Sustentabilidade e Lucratividade.',
    metaKeywords: ['Carbono', 'ESG', 'Amazonia'],
    tags: ['ESG', 'Preservação'],
    author: { name: 'Eleonora Bittencourt', avatarUrl: `${AVATAR_PATH}/eleonora_bittencourt.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '15',
    title: 'Energia Limpa e Mineração Sustentável',
    slug: 'energia-limpa-mineracao',
    description: 'Utilizando excedentes de energia solar para alimentar a rede blockchain.',
    content: '<p>Nossa infraestrutura é alimentada 100% por fontes renováveis...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    totalViews: 5800,
    totalShares: 220,
    totalComments: 12,
    totalFavorites: 190,
    metaTitle: 'Energia Limpa | ASPPIBRA DAO',
    metaDescription: 'Mineração e Sustentabilidade.',
    metaKeywords: ['Energia Solar', 'Mineração', 'Blockchain'],
    tags: ['Energia', 'Eco'],
    author: { name: 'Thiago Mendes', avatarUrl: `${AVATAR_PATH}/thiago_mendes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '16',
    title: 'O Impacto da Tokenização no Agro Sustentável',
    slug: 'impacto-tokenizacao-agro',
    description: 'Como o rastreamento on-chain garante produtos livres de desmatamento.',
    content: '<p>A rastreabilidade é a maior ferramenta de proteção ambiental...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    totalViews: 8100,
    totalShares: 410,
    totalComments: 30,
    totalFavorites: 295,
    metaTitle: 'Agro Sustentável | ASPPIBRA DAO',
    metaDescription: 'Rastreabilidade e Proteção.',
    metaKeywords: ['Agro', 'Rastreabilidade', 'ESG'],
    tags: ['Agro', 'ESG'],
    author: { name: 'Arthur Guimarães', avatarUrl: `${AVATAR_PATH}/arthur_guimaraes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '25',
    title: 'Água como Ativo Tokenizado: A Nova Fronteira',
    slug: 'agua-ativo-tokenizado',
    description: 'Garantindo o acesso e a preservação de recursos hídricos via governança.',
    content: '<p>A água é o recurso mais valioso do planeta e precisa de proteção digital...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    totalViews: 14000,
    totalShares: 1100,
    totalComments: 62,
    totalFavorites: 980,
    metaTitle: 'Gestão Hídrica | ASPPIBRA DAO',
    metaDescription: 'Tokenização e preservação de água.',
    metaKeywords: ['Água', 'Recursos', 'DAO'],
    tags: ['Natureza', 'Sustentabilidade'],
    author: { name: 'Eleonora Bittencourt', avatarUrl: `${AVATAR_PATH}/eleonora_bittencourt.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '26',
    title: 'Biodiversidade e NFTs de Genética Vegetal',
    slug: 'biodiversidade-nfts-genetica',
    description: 'Protegendo o patrimônio genético brasileiro contra a biopirataria.',
    content: '<p>Nossas sementes são nosso maior tesouro intelectual e biológico...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    totalViews: 5200,
    totalShares: 140,
    totalComments: 4,
    totalFavorites: 115,
    metaTitle: 'Biodiversidade | ASPPIBRA DAO',
    metaDescription: 'Proteção genética on-chain.',
    metaKeywords: ['Biodiversidade', 'NFT', 'Genética'],
    tags: ['Ciência', 'Eco'],
    author: { name: 'Lívia Guedes', avatarUrl: `${AVATAR_PATH}/livia_guedes.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '27',
    title: 'Cidades Verdes e a Tokenização Urbana',
    slug: 'cidades-verdes-tokenizacao-urbana',
    description: 'Como transformar centros urbanos em sumidouros de carbono inteligentes.',
    content: '<p>O futuro das cidades é verde, digital e descentralizado...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    totalViews: 7300,
    totalShares: 280,
    totalComments: 19,
    totalFavorites: 310,
    metaTitle: 'Urbanismo Verde | ASPPIBRA DAO',
    metaDescription: 'Tecnologia aplicada às cidades.',
    metaKeywords: ['Cidades', 'Smart Cities', 'Carbono'],
    tags: ['Urbanismo', 'Sustentabilidade'],
    author: { name: 'Carolina Alves', avatarUrl: `${AVATAR_PATH}/carolina_alves.png` },
    comments: [],
    favoritePerson: [],
  },
  {
    id: '28',
    title: 'Oceanos Limpos: Monitoramento via Satélite e Web3',
    slug: 'oceanos-limpos-monitoramento',
    description: 'Lutando contra a poluição plástica com incentivos econômicos diretos.',
    content: '<p>A saúde dos oceanos reflete a saúde da nossa economia global...</p>',
    coverUrl: '/assets/images/covers/Petroleo-Fallback.png',
    category: 'Meio Ambiente',
    status: 'published',
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    totalViews: 4900,
    totalShares: 160,
    totalComments: 8,
    totalFavorites: 145,
    metaTitle: 'Oceanos e Web3 | ASPPIBRA DAO',
    metaDescription: 'Monitoramento e preservação marinha.',
    metaKeywords: ['Oceanos', 'Satélite', 'Web3'],
    tags: ['Oceano', 'Inovação'],
    author: { name: 'Eleonora Bittencourt', avatarUrl: `${AVATAR_PATH}/eleonora_bittencourt.png` },
    comments: [],
    favoritePerson: [],
  },
];

export const COMMUNITIES_MOCK = [
  {
    name: 'CoinTelegraph',
    logo: '/assets/icons/communities/cointelegraph.svg',
    url: 'https://cointelegraph.com',
  },
  {
    name: 'Binance Academy',
    logo: '/assets/icons/communities/binance.svg',
    url: 'https://academy.binance.com',
  },
  { name: 'Ethereum Org', logo: '/assets/icons/communities/eth.svg', url: 'https://ethereum.org' },
  { name: 'CoinDesk', logo: '/assets/icons/communities/coindesk.svg', url: 'https://coindesk.com' },
  {
    name: 'CryptoPanic',
    logo: '/assets/icons/communities/cryptopanic.svg',
    url: 'https://cryptopanic.com',
  },
  {
    name: 'Solana Foundation',
    logo: '/assets/icons/communities/solana.svg',
    url: 'https://solana.com',
  },
];

export const VIDEOS_MOCK = {
  brazil: [
    {
      id: 'HPQeQwPahR0',
      title: 'O MAIOR ROUBO “LEGAL” de BITCOIN da HISTÓRIA!',
      channel: 'O Primo Rico',
      thumbnail: 'https://img.youtube.com/vi/HPQeQwPahR0/maxresdefault.jpg',
      postedAt: '2 dias atrás',
      duration: '12:40',
    },
    {
      id: 'hLMnCVEDjqE',
      title: '🔥 TUDO sobre a XRP em 2025! Vale a pena investir agora?',
      channel: 'É TopSaber',
      thumbnail: 'https://img.youtube.com/vi/hLMnCVEDjqE/maxresdefault.jpg',
      postedAt: '5 horas atrás',
      duration: '08:15',
    },
    {
      id: 'Xc6juEgNwog',
      title: 'URGENTE: FED VAI INJETAR TRILHÕES NO MERCADO',
      channel: 'Investidor 4.20',
      thumbnail: 'https://img.youtube.com/vi/Xc6juEgNwog/maxresdefault.jpg',
      postedAt: '1 dia atrás',
      duration: '15:20',
    },
    {
      id: 'x43e3g-JWWQ',
      title: 'MEMECOINS: POR QUE COMPRAR? Estratégias para 2024',
      channel: 'Bruno Perini',
      thumbnail: 'https://img.youtube.com/vi/x43e3g-JWWQ/maxresdefault.jpg',
      postedAt: '3 dias atrás',
      duration: '22:00',
    },
  ],
  international: [
    {
      id: 'W4mGv_8W-7I',
      title: 'Bitcoin Strategy for 2025: The Institutional Era',
      channel: 'Michael Saylor',
      thumbnail: 'https://img.youtube.com/vi/W4mGv_8W-7I/maxresdefault.jpg',
      postedAt: '1 dia atrás',
      duration: '18:10',
    },
    {
      id: 'mS7S5E-WlqU',
      title: 'Ethereum Roadmap: Beyond the Merge',
      channel: 'Vitalik Buterin',
      thumbnail: 'https://img.youtube.com/vi/mS7S5E-WlqU/maxresdefault.jpg',
      postedAt: '4 dias atrás',
      duration: '25:45',
    },
    {
      id: 'N64vL67520Q',
      title: 'Why Solana is Winning the L1 Wars in 2024',
      channel: 'Coin Bureau',
      thumbnail: 'https://img.youtube.com/vi/N64vL67520Q/maxresdefault.jpg',
      postedAt: '6 horas atrás',
      duration: '14:20',
    },
    {
      id: 'fB05fV7X_7o',
      title: 'Global Macro: The Debt Crisis Explained',
      channel: 'Raoul Pal',
      thumbnail: 'https://img.youtube.com/vi/fB05fV7X_7o/maxresdefault.jpg',
      postedAt: '12 horas atrás',
      duration: '32:00',
    },
  ],
};
